// Repo walking + incremental indexing. Walks the tree once, skipping the usual
// noise dirs and binary/large files, and (re)parses only files whose mtime
// changed since the last build. The result is cached to disk by store.ts.

import { promises as fs } from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { getParser } from "./parser.js";
import { loadIndex, saveIndex, INDEX_VERSION, type CodeIndex, type FileEntry } from "./store.js";

const IGNORE_DIRS = new Set([
  ".git", "node_modules", "dist", "build", "out", ".next", ".nuxt", "target",
  "__pycache__", ".venv", "venv", "env", ".idea", ".vscode", "coverage",
  ".slimdex", ".cache", "vendor", "bin", "obj", ".gradle", ".mvn",
  // Salesforce DX writes generated apex/lwc typings here — thousands of lines
  // of machine output with no symbols worth indexing.
  ".sfdx", ".sf",
  // Framework/tooling build output and package caches. Every one of these is
  // machine-written; none is a plausible name for hand-edited source. Kept out
  // of the list on purpose: `assets`, `public`, `static` — those hold real
  // source in plenty of repos, so bundles living there are caught by the
  // minified-content check below instead of by name.
  ".output", ".svelte-kit", ".astro", ".docusaurus", ".parcel-cache", ".turbo",
  ".angular", ".expo", ".serverless", ".terraform", ".yarn", ".pnpm-store",
  "bower_components", "jspm_packages", "site-packages",
  ".tox", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".nyc_output",
  ".dart_tool", "DerivedData", "Pods",
  "cmake-build-debug", "cmake-build-release",
  // Generated API documentation. Found by corpus audit, not by guessing: on a
  // real Swift repo, 336 of 440 indexed files (76%) were jazzy-generated HTML
  // and CSS under docs/ and .docset — 700-800 lines each, ~0 symbols, crowding
  // every search the way the minified bundles did. These directory names are
  // tool-owned outputs; `docs/` itself is NOT here, because plenty of repos
  // keep hand-written documentation there.
  ".docset", "htmlcov", "_site", ".jekyll-cache", "storybook-static",
]);

// A minified bundle is indistinguishable from source by extension (`.js` is
// `.js`) and by name once a build tool hashes it — `index-B7xK2p9q.js` looks
// exactly like source. What it can't hide is its shape: bundlers strip the
// newlines, so one line runs for tens of thousands of characters. Real source
// does not, at any indent depth or line width a human tolerates.
//
// This is the check that pays: 2.5MB of untracked bundles under a
// `static/assets/` directory once made roughly a third of this repo's search
// results unusable, and no reasonable default DIRECTORY list would have caught
// it — the directory was named `assets`.
const MINIFIED_LINE_CHARS = 5000;

/**
 * Machine-written documentation: javadoc, Doxygen, jazzy, Sphinx, MkDocs,
 * rustdoc, static-site generators.
 *
 * Directory names cannot catch this and the corpus audit proved it: on a real
 * Swift repo, 332 of 440 indexed files were jazzy HTML sitting in plain `docs/`
 * — a directory no one can ignore by default, because just as many repos keep
 * hand-written documentation there. One of them lived in `Alamofire.docset`,
 * which a basename ignore list also misses.
 *
 * What every generator does leave is a signature in its own output. That is the
 * same trade as looksMinified: identify build output by what it IS, not by where
 * it happens to sit.
 *
 * Scoped to the head of the file — a generator stamp appears in the first
 * kilobyte or not at all — so a hand-written page that merely mentions the word
 * "generated" further down is unaffected.
 */
// Two signatures, because the obvious one is not enough — verified against real
// output rather than assumed. A first pass looked only for `<meta
// name="generator">` and a "Generated by <tool>" comment, and caught none of
// Alamofire's 332 jazzy pages: jazzy writes neither. What it does write, in
// every file, is its own asset links and Dash anchors. So the second pattern
// matches the stylesheets and scripts these tools ship, which is the part a
// generator cannot omit without breaking its own output.
const GENERATOR_MARKERS =
  /<meta\s+name=["']generator["']|generated by (?:javadoc|doxygen|jazzy|sphinx|mkdocs|rustdoc|godoc|jsdoc|typedoc|scaladoc|kdoc)/i;
const GENERATOR_ASSETS =
  /(?:jazzy|doxygen|javadoc|pygments|documentation_options|rustdoc|typedoc|jsdoc|epydoc|scaladoc)\.(?:css|js)|class=["']dashAnchor|apple_ref\//i;

export function looksGeneratedDoc(source: string): boolean {
  const head = source.slice(0, 4096);
  return GENERATOR_MARKERS.test(head) || GENERATOR_ASSETS.test(head);
}

export function looksMinified(source: string): boolean {
  // Scan for a single overlong line without splitting the whole string — these
  // are the biggest files in the repo and splitting them is what we're avoiding.
  let lineStart = 0;
  for (let i = 0; i < source.length; i++) {
    if (source.charCodeAt(i) === 10 /* \n */) {
      if (i - lineStart > MINIFIED_LINE_CHARS) return true;
      lineStart = i + 1;
    }
  }
  return source.length - lineStart > MINIFIED_LINE_CHARS;
}

const CODE_EXT = new Set([
  ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".py", ".go", ".rs",
  ".java", ".cs", ".rb", ".php", ".c", ".h", ".cpp", ".hpp", ".cc",
  ".kt", ".swift", ".scala", ".m", ".mm", ".vue", ".svelte",
  // Apex. Syntactically Java-like, so the existing Java/C# rules find its
  // classes and methods without needing rules of their own.
  ".cls", ".trigger",
  // Markup and styles. These carry few or no code symbols (verified: CSS → 0,
  // SCSS surfaces only real `@function` decls, HTML only inline <script> funcs —
  // no junk), but indexing them makes them searchable/readable through slimdex,
  // which frontend and LWC repos (HTML templates + CSS/SCSS alongside JS/Apex)
  // genuinely need. read_lines / search_code / get_file_skeleton then work on them.
  ".css", ".scss", ".less", ".html", ".htm",
]);

/**
 * Files matched by NAME SUFFIX rather than extension.
 *
 * Salesforce pairs every deployable component with a metadata sidecar:
 * `AccountSvc.cls-meta.xml`, `errorPanel.js-meta.xml`,
 * `Account.object-meta.xml`. They decide API version, visibility, exposure and
 * field-level security — a Salesforce developer searches them constantly ("which
 * permission set grants this field?") — and they were invisible, because slimdex
 * matches on `path.extname()` and that returns `.xml`.
 *
 * Adding `.xml` to CODE_EXT would have worked and been wrong: it also swallows
 * pom.xml, web.xml, every Spring context and every config tree in the repo,
 * recreating precisely the index-noise problem the minified and generated-doc
 * checks just removed. The suffix is the part that carries the meaning, so the
 * suffix is what to match.
 *
 * These carry no code symbols — same standing as CSS and HTML: indexed so
 * search_code, read_lines and get_file_skeleton reach them, not because a
 * `<fullName>` is a declaration the symbol tools should resolve.
 */
const INDEX_SUFFIXES = ["-meta.xml"];

/** Does this filename qualify by suffix, independent of its extension? */
export function hasIndexedSuffix(name: string, suffixes: string[] = INDEX_SUFFIXES): boolean {
  const lower = name.toLowerCase();
  return suffixes.some((s) => lower.endsWith(s));
}

const MAX_FILE_BYTES = 1_500_000; // skip anything larger; almost certainly generated

export function toPosix(p: string): string {
  return p.split(path.sep).join("/");
}

/**
 * Is this repo-relative posix path inside `prefix`, respecting DIRECTORY
 * boundaries?
 *
 * A bare `startsWith` does not: prefix "s" matched src/, scripts/ AND
 * smoke-test.mjs, and prefix "src" matched a sibling "src-old/" — so scoping a
 * search could silently widen it instead of narrowing it, which is the one
 * thing a scoping argument must never do. The correct comparison already
 * existed twice in this codebase (repo_map's drill-down, digest.ts's isCovered);
 * this is that rule, in one place, for every pathPrefix to share.
 *
 * An empty prefix means "no filter" rather than "matches nothing".
 */
/**
 * Does a path.relative() result point OUTSIDE the base it was computed from?
 *
 * `rel.startsWith("..")` is the obvious test and it is wrong in both
 * directions' worth of care: it also rejects legitimate in-root names that
 * merely begin with two dots, like `..cache/file.ts`. Only a `..` segment —
 * the whole string, or `..` followed by a separator — actually means "above
 * the base". An absolute result means the two paths share no root at all
 * (different drive on Windows), which is also outside.
 */
export function escapesBase(rel: string): boolean {
  return rel === ".." || rel.startsWith(".." + path.sep) || rel.startsWith("../") || path.isAbsolute(rel);
}

export function underPrefix(file: string, prefix: string): boolean {
  const p = toPosix(prefix).replace(/\/+$/, "");
  if (!p) return true;
  return file === p || file.startsWith(p + "/");
}

// Optional per-repo config at <root>/.slimdex.json:
//   { "ignoreDirs": ["fixtures"], "extensions": [".astro"], "exclude": ["generated/"],
//     "maxFileBytes": 2000000 }
interface SlimdexConfig {
  ignoreDirs: Set<string>; // matched against a directory's BASENAME
  // Multi-segment ignoreDirs entries ("backend/static/assets"). The walk
  // compares a directory's basename, so a path-shaped entry used to be accepted,
  // counted in the "+N ignoreDirs" summary, and then match nothing — a config
  // that reported success and did nothing, which is worse than a rejection.
  // These are matched against the repo-relative posix path of the directory.
  ignorePaths: string[];
  /** Filename suffixes indexed regardless of extension (see INDEX_SUFFIXES). */
  suffixes: string[];
  extensions: Set<string>;
  exclude: string[]; // substring match against repo-relative posix path
  maxFileBytes: number;
  // Reported back to the caller so a typo'd key or malformed JSON is visible in
  // index_repo's output. Silently swallowing config errors made a broken
  // .slimdex.json indistinguishable from having none at all.
  present: boolean;
  warnings: string[];
  summary: string;
}

const KNOWN_KEYS = new Set(["ignoreDirs", "extensions", "exclude", "maxFileBytes", "suffixes"]);

async function loadConfig(root: string): Promise<SlimdexConfig> {
  const ignoreDirs = new Set(IGNORE_DIRS);
  const ignorePaths: string[] = [];
  const suffixes = [...INDEX_SUFFIXES];
  const extensions = new Set(CODE_EXT);
  const exclude: string[] = [];
  const warnings: string[] = [];
  let maxFileBytes = MAX_FILE_BYTES;
  let present = false;
  const added = { ignoreDirs: 0, extensions: 0, exclude: 0, suffixes: 0 };

  let raw: string;
  try {
    raw = await fs.readFile(path.join(root, ".slimdex.json"), "utf8");
    present = true;
  } catch {
    return { ignoreDirs, ignorePaths, suffixes, extensions, exclude, maxFileBytes, present: false, warnings, summary: "no .slimdex.json (defaults)" };
  }

  let cfg: Record<string, unknown>;
  try {
    cfg = JSON.parse(raw);
  } catch (e) {
    warnings.push(`.slimdex.json is not valid JSON (${(e as Error).message}) — ignoring it and using defaults`);
    return { ignoreDirs, ignorePaths, suffixes, extensions, exclude, maxFileBytes, present, warnings, summary: "invalid .slimdex.json" };
  }

  for (const key of Object.keys(cfg)) {
    if (!KNOWN_KEYS.has(key)) warnings.push(`unknown key "${key}" in .slimdex.json (known: ${[...KNOWN_KEYS].join(", ")})`);
  }

  const asArray = (key: string): unknown[] => {
    const v = cfg[key];
    if (v === undefined) return [];
    if (!Array.isArray(v)) {
      warnings.push(`"${key}" must be an array — ignored`);
      return [];
    }
    return v;
  };

  for (const d of asArray("ignoreDirs")) {
    // Tolerate both shapes rather than making the user guess which one the
    // walker uses: a bare name matches any directory so called, anywhere; a
    // path-shaped entry is anchored at the repo root. Trailing slashes and
    // leading "./" are normalised away so the obvious spellings all work.
    const raw = toPosix(String(d).replace(/\\/g, "/")).replace(/^\.\//, "").replace(/\/+$/, "");
    if (!raw) {
      warnings.push(`empty ignoreDirs entry — ignored`);
      continue;
    }
    if (raw.includes("/")) ignorePaths.push(raw);
    else ignoreDirs.add(raw);
    added.ignoreDirs++;
  }
  for (const e of asArray("extensions")) {
    const ext = String(e).toLowerCase();
    if (!ext.startsWith(".")) warnings.push(`extension "${e}" should start with a dot`);
    extensions.add(ext);
    added.extensions++;
  }
  for (const x of asArray("exclude")) {
    exclude.push(toPosix(String(x)));
    added.exclude++;
  }
  // Filename suffixes, for the same reason Salesforce needed one built in: a
  // repo's meaningful files are not always identifiable by extension.
  // `.d.ts`, `.spec.ts`, `.stories.tsx`, `Dockerfile.prod` are all suffix-shaped.
  for (const s of asArray("suffixes")) {
    const suf = String(s).toLowerCase();
    if (!suf) {
      warnings.push(`empty suffixes entry — ignored`);
      continue;
    }
    // A leading dot would be an extension, which `extensions` already handles;
    // saying so beats silently accepting a duplicate mechanism.
    if (/^\.[a-z0-9]+$/.test(suf)) warnings.push(`"${s}" looks like an extension — put it in "extensions", not "suffixes"`);
    suffixes.push(suf);
    added.suffixes++;
  }
  if (cfg.maxFileBytes !== undefined) {
    const n = Number(cfg.maxFileBytes);
    if (Number.isFinite(n) && n > 0) maxFileBytes = n;
    else warnings.push(`"maxFileBytes" must be a positive number — using default ${MAX_FILE_BYTES}`);
  }

  const summary =
    `.slimdex.json loaded (+${added.ignoreDirs} ignoreDirs, +${added.extensions} extensions, ` +
    `${added.exclude} exclude rules, +${added.suffixes} suffixes, maxFileBytes ${maxFileBytes})`;
  return { ignoreDirs, ignorePaths, suffixes, extensions, exclude, maxFileBytes, present, warnings, summary };
}

async function walk(root: string, dir: string, acc: string[], cfg: SlimdexConfig): Promise<void> {
  let entries: import("node:fs").Dirent[];
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (cfg.ignoreDirs.has(e.name)) continue;
      // underPrefix, not startsWith: an ignorePath of "src/gen" must not also
      // swallow a sibling "src/generated".
      const relDir = toPosix(path.relative(root, full));
      if (cfg.ignorePaths.some((p) => underPrefix(relDir, p))) continue;
      await walk(root, full, acc, cfg);
    } else if (e.isFile()) {
      if (!cfg.extensions.has(path.extname(e.name).toLowerCase()) && !hasIndexedSuffix(e.name, cfg.suffixes)) continue;
      const rel = toPosix(path.relative(root, full));
      if (cfg.exclude.some((x) => rel.includes(x))) continue;
      acc.push(full);
    }
  }
}

export interface IndexResult {
  index: CodeIndex;
  parsed: number;
  reused: number;
  removed: number;
  totalFiles: number;
  skipped: number; // over maxFileBytes
  generated: number; // build output detected by content, not by name
  // Files that were already indexed and whose CONTENT moved — an edit, as
  // opposed to a new file or a touched mtime. This is the only handle slimdex
  // has on edits made through other tools, and it powers the write-discipline
  // half of `stats`.
  changedPaths: string[];
  truncated: number; // files whose symbol list hit the safety cap
  parser: string;
  config: string; // human-readable config summary
  warnings: string[];
}

export async function buildOrRefresh(root: string, force = false): Promise<IndexResult> {
  // loadIndex now returns a cached object shared with every other caller, and
  // the loop below assigns into `index.files`. Copy the map first so a refresh
  // in progress can never mutate what other tool calls are reading. Entries are
  // replaced wholesale rather than edited, so a shallow copy is sufficient.
  const loaded = await loadIndex(root);
  const index: CodeIndex = force
    ? { version: INDEX_VERSION, builtAt: "", files: {} }
    : { ...loaded, files: { ...loaded.files } };

  const cfg = await loadConfig(root);
  const files: string[] = [];
  await walk(root, root, files, cfg);

  const present = new Set<string>();
  const parser = getParser();
  let parsed = 0;
  let reused = 0;
  let skipped = 0;
  let generated = 0;
  const changedPaths: string[] = [];

  for (const full of files) {
    const rel = toPosix(path.relative(root, full));
    present.add(rel);
    let stat: import("node:fs").Stats;
    try {
      stat = await fs.stat(full);
    } catch {
      continue;
    }
    if (stat.size > cfg.maxFileBytes) {
      skipped++;
      present.delete(rel); // not indexed, so don't treat it as still-present
      continue;
    }

    const existing = index.files[rel];
    if (existing && existing.mtimeMs === stat.mtimeMs) {
      reused++;
      continue;
    }
    let source: string;
    try {
      source = await fs.readFile(full, "utf8");
    } catch {
      continue;
    }
    if (looksMinified(source) || looksGeneratedDoc(source)) {
      generated++;
      present.delete(rel);
      delete index.files[rel]; // may have been indexed before this check existed
      continue;
    }
    const contentHash = createHash("sha256").update(source).digest("hex");
    // mtime moving is not an edit — a checkout, a copy or a formatter that wrote
    // identical bytes all bump it. Only a different hash on a file we had
    // already indexed is a real content change, and this whole metric is worth
    // nothing if it cries wolf.
    // Compared against what was on disk BEFORE this build, not against the
    // working index: `force` empties the latter, and a forced rebuild must not
    // silently report zero edits just because it threw its own baseline away.
    const prior = loaded.files[rel];
    if (prior && prior.contentHash !== contentHash) changedPaths.push(rel);
    const extracted = parser.extractSymbols(source, 2001);
    const entry: FileEntry = {
      mtimeMs: stat.mtimeMs,
      contentHash,
      lines: source.split(/\r?\n/).length,
      symbols: extracted.slice(0, 2000),
      symbolsTruncated: extracted.length > 2000,
      imports: parser.extractImports(source),
    };
    index.files[rel] = entry;
    parsed++;
  }

  // drop deleted files
  let removed = 0;
  for (const rel of Object.keys(index.files)) {
    if (!present.has(rel)) {
      delete index.files[rel];
      removed++;
    }
  }

  const truncated = Object.values(index.files).filter((entry) => entry.symbolsTruncated).length;
  await saveIndex(root, index);
  return {
    index,
    parsed,
    reused,
    removed,
    totalFiles: present.size,
    skipped,
    generated,
    changedPaths,
    truncated,
    parser: parser.name,
    config: cfg.summary,
    warnings: cfg.warnings,
  };
}
